# -*- coding: utf-8 -*-
"""DAY  2 : ASSIGNMENT 02-PYTHON ASSIGNMENT.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DxD9EsK6l1eaUrRkPNlal2U07xq2uZS_

DAY 2 ASSIGNMENT 2
"""

L = ["Ram", 1, "Shyam", 2, "Aman", 3]
strings = [x for x in L if isinstance(x, str)]
numbers = [x for x in L if isinstance(x, int)]
strings.sort()
numbers.sort()
sorted_list = strings + numbers
print("Original list:", L)
print("Sorted list:", sorted_list)